#!/usr/bin/env python3
"""
Script to help implement Razorpay webhook security
This will guide you through the process
"""

print("=" * 70)
print("RAZORPAY WEBHOOK SECURITY IMPLEMENTATION GUIDE")
print("=" * 70)
print()

print("STEP 1: Get Webhook Secrets from Razorpay Dashboard")
print("-" * 70)
print()
print("1. Go to: https://dashboard.razorpay.com/")
print("2. Navigate to: Settings → Webhooks")
print("3. For each webhook (Razorpay and Split Razorpay):")
print("   - Click on the webhook")
print("   - Copy the 'Webhook Secret' (starts with 'whsec_')")
print()
print("You need TWO webhook secrets:")
print("   - Razorpay Webhook Secret")
print("   - Split Razorpay Webhook Secret")
print()

input("Press Enter when you have both webhook secrets...")

print()
print("STEP 2: Add Secrets to .env File")
print("-" * 70)
print()
print("Run these commands on your server:")
print()
print("cd /var/www/scan2food/application/scan2food")
print("nano .env")
print()
print("Add these lines at the end:")
print()
print("# Razorpay Webhook Secrets")
print("RAZORPAY_WEBHOOK_SECRET=your_razorpay_webhook_secret_here")
print("SPLIT_RAZORPAY_WEBHOOK_SECRET=your_split_razorpay_webhook_secret_here")
print()
print("Replace 'your_razorpay_webhook_secret_here' with actual secrets")
print()
print("Save and exit (Ctrl+X, then Y, then Enter)")
print()

input("Press Enter when .env is updated...")

print()
print("STEP 3: Update Database Model")
print("-" * 70)
print()
print("The PaymentGateway model needs to be updated:")
print()
print("CHANGE:")
print("  gateway_salt = models.CharField(...)")
print()
print("TO:")
print("  webhook_secret = models.CharField(max_length=200, null=True, blank=True)")
print()
print("This change will be applied in the code files I create.")
print()

input("Press Enter to continue...")

print()
print("STEP 4: Run Database Migration")
print("-" * 70)
print()
print("After code changes, run:")
print()
print("cd /var/www/scan2food/application/scan2food")
print("source venv/bin/activate")
print("python manage.py makemigrations")
print("python manage.py migrate")
print()

input("Press Enter to continue...")

print()
print("STEP 5: Update Webhook Secret in Admin Panel")
print("-" * 70)
print()
print("1. Go to: https://calculatentrade.com/admin/")
print("2. Navigate to: AdminPortal → Payment gateways")
print("3. For 'Razorpay' gateway:")
print("   - Click to edit")
print("   - Remove value from 'Gateway salt' (if any)")
print("   - Add webhook secret to 'Webhook secret' field")
print("   - Save")
print()
print("4. Repeat for 'split_razorpay' gateway")
print()

input("Press Enter to continue...")

print()
print("STEP 6: Restart Services")
print("-" * 70)
print()
print("sudo systemctl restart gunicorn")
print("sudo systemctl restart daphne")
print()

input("Press Enter to continue...")

print()
print("STEP 7: Test Webhook Security")
print("-" * 70)
print()
print("Test 1: Real Payment (Should Work)")
print("  - Create a test order")
print("  - Complete payment")
print("  - Order should be confirmed ✅")
print()
print("Test 2: Fake Webhook (Should Fail)")
print("  - Use Postman to send POST to webhook URL")
print("  - Should return error ❌")
print()

print()
print("=" * 70)
print("IMPLEMENTATION COMPLETE!")
print("=" * 70)
print()
print("Your Razorpay webhooks are now secure!")
print()
print("Key Security Improvements:")
print("✅ Webhook signature verification")
print("✅ Secrets stored in .env (not in database)")
print("✅ Protection against fake payment attacks")
print()
