"""
Django settings for theatreApp project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^u_*nzz-$&m6jeyj=mml8rmp8^7btom(sj9(r3kb8_#uxn$f^*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['165.22.219.111', '134.209.149.31', 'scan2food.com', 'www.scan2food.com', 'localhost', '127.0.0.1', '192.168.1.33']

# ALLOW CSRF ORIGINS
CORS_ALLOWED_ORIGINS = [
    'https://scan2food.com',  # Replace with your actual domain
    'https://www.scan2food.com',  # If applicable, add the www version as well
    "https://sandbox.cashfree.com",
    "https://api.cashfree.com"
]

# Allow CSRF Token
CSRF_TRUSTED_ORIGINS = [
    'https://scan2food.com',  # Replace with your actual domain
    'https://www.scan2food.com',  # If applicable, add the www version as well
    "https://api.cashfree.com",
    "https://sandbox.cashfree.com",
]

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'website',
    'theatre',
    'adminPortal',
    'chat_bot',
    'chat_box',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'theatreApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'theatreApp.wsgi.application'

ASGI_APPLICATION = 'theatreApp.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],  # Use your Redis host/port
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import os

# Check if we're in production (you can set this environment variable on server)
if os.environ.get('DJANGO_ENV') == 'production':
    # PRODUCTION: PostgreSQL with NEW secure credentials
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'scan2food_db'),
            'USER': os.environ.get('DB_USER', 'scan2food_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'CHANGE_THIS_PASSWORD'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    # LOCAL DEVELOPMENT: Using SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# OLD CREDENTIALS (COMPROMISED - DO NOT USE):
# USER: 'guru'
# PASSWORD: 'guru@2003'
# These credentials are known to old developer - NEVER use them!

# Caches
# cashing for the application
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # 1 is the Redis DB number
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

# LOCAL DEVELOPMENT: Serve directly from source files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR.parent.parent, 'static_files', 'scan2food-static', 'static'),
]

# STATIC_ROOT not needed for local development with runserver
# Uncomment for production deployment
# STATIC_ROOT = os.path.join(BASE_DIR.parent.parent, 'staticfiles_collected')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'theatre:index'
LOGIN_URL = 'login'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# LOCAL DEVELOPMENT: Disable secure cookies for localhost
SESSION_COOKIE_SAMESITE = 'Lax'  # Changed from 'None' for local dev
SESSION_COOKIE_SECURE = False  # Changed from True for local dev (http://)
CSRF_COOKIE_SAMESITE = 'Lax'  # Changed from 'None' for local dev
CSRF_COOKIE_SECURE = False  # Changed from True for local dev (http://)

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 1 day