# Generated by Django 5.1.1 on 2025-09-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_user',
        ),
        migrations.DeleteModel(
            name='ChatUser',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
