# Generated by Django 5.1.1 on 2024-12-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_payment_payout_alter_order_seat_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theatre.order'),
        ),
    ]
