# Generated by Django 5.1.1 on 2024-12-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_theatre_email_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='category_image',
            field=models.ImageField(default='default_food_img.png', upload_to='category_images'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
