# Generated by Django 5.1.1 on 2024-12-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_foodcategory_category_image_fooditem_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
