# Generated by Django 5.1.1 on 2024-12-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_payment_is_settled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
