# Generated by Django 5.1.1 on 2024-12-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='category_image',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
