# Generated by Django 5.1.1 on 2025-01-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0007_remove_foodcategory_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CashFreePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashfree_order_id', models.CharField(db_index=True, default='', max_length=500, unique=True)),
                ('payment_session_id', models.CharField(default='', max_length=500, unique=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theatre.payment')),
            ],
        ),
        migrations.CreateModel(
            name='RazorpayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=255)),
                ('razorpay_payment_id', models.CharField(max_length=255)),
                ('razorpay_signature', models.CharField(max_length=255)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theatre.payment')),
            ],
        ),
    ]
