# Generated by Django 5.1.1 on 2025-01-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0008_remove_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['priority_number']},
        ),
        migrations.AddField(
            model_name='fooditem',
            name='priority_number',
            field=models.IntegerField(default=1),
        ),
    ]
