# Generated by Django 5.1.1 on 2025-02-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0009_alter_fooditem_options_fooditem_priority_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='on_mrp',
            field=models.BooleanField(default=False),
        ),
    ]
