# Generated by Django 5.1.1 on 2025-02-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0010_fooditem_on_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theatre.fooditem'),
        ),
    ]
