# Generated by Django 5.1.1 on 2025-02-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0011_orderitems_food_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
