# Generated by Django 5.1.1 on 2025-02-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0012_fooditem_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
