# Generated by Django 5.1.1 on 2025-03-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0013_alter_fooditem_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='settlement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='theatre',
            name='notification_numbers',
            field=models.CharField(blank=True, default='', max_length=21),
        ),
        migrations.AddField(
            model_name='theatre',
            name='query_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
