# Generated by Django 5.1.1 on 2025-04-09 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0014_payment_settlement_theatre_notification_numbers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonepePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.CharField(db_index=True, default='', max_length=500, unique=True)),
                ('order_id', models.CharField(db_index=True, default='', max_length=500, unique=True)),
                ('payment_url', models.CharField(default='', max_length=1500)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theatre.payment')),
            ],
        ),
    ]
