# Generated by Django 5.1.1 on 2025-04-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0015_phonepepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_comp',
            field=models.CharField(choices=[('DOP AGENT SOFTWARE', 'DOP AGENT SOFTWARE'), ('SCAN2FOOD', 'SCAN2FOOD')], default='DOP AGENT SOFTWARE', max_length=20),
        ),
    ]
