# Generated by Django 5.1.1 on 2025-04-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0016_payment_invoice_comp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_perscantage', models.IntegerField()),
                ('message', models.CharField(default='', max_length=200)),
                ('is_valid', models.BooleanField(default=False)),
                ('theatre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre')),
            ],
        ),
    ]
