# Generated by Django 5.1.1 on 2025-05-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0017_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_shown',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_comp',
            field=models.CharField(choices=[('DOP AGENT SOFTWARE', 'DOP AGENT SOFTWARE'), ('SCAN2FOOD', 'SCAN2FOOD')], default='SCAN2FOOD', max_length=20),
        ),
    ]
