# Generated by Django 5.1.1 on 2025-05-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0018_order_is_shown_alter_payment_invoice_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_shown',
            field=models.BooleanField(default=False),
        ),
    ]
