# Generated by Django 5.1.1 on 2025-05-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0019_alter_order_is_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='made_by',
            field=models.CharField(choices=[('packaged', 'Packaged'), ('in-house', 'In House'), ('third-party', 'Third Party')], default='in-house', max_length=15),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='unavailable_by',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=15),
        ),
    ]
