# Generated by Django 5.1.1 on 2025-05-26 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0020_fooditem_made_by_fooditem_unavailable_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCAvenuePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('traking_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('bank_ref_no', models.CharField(db_index=True, max_length=500, unique=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theatre.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PayuPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('order_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theatre.payment')),
            ],
        ),
    ]
