# Generated by Django 5.1.1 on 2025-06-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0021_ccavenuepayment_payupayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otp_timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_otp',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='theatre',
            name='otp',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='theatre',
            name='otp_person_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='theatre',
            name='otp_phone_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='theatre',
            name='otp_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
