# Generated by Django 5.1.1 on 2025-07-04 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0022_order_otp_timing_order_refund_otp_theatre_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='on_mrp',
        ),
        migrations.AddField(
            model_name='theatre',
            name='service_end_time',
            field=models.TimeField(default=datetime.time(23, 45)),
        ),
    ]
