# Generated by Django 5.1.1 on 2025-07-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0023_remove_fooditem_on_mrp_theatre_service_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='group',
            field=models.CharField(default='', max_length=200),
        ),
    ]
