# Generated by Django 5.1.1 on 2025-07-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0024_theatre_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonepepayment',
            name='refund_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
