# Generated by Django 5.1.1 on 2025-07-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0025_phonepepayment_refund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='order_limit',
            field=models.IntegerField(default=25),
        ),
    ]
