# Generated by Django 5.1.1 on 2025-08-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0026_theatre_order_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='max_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='min_time',
            field=models.IntegerField(default=5),
        ),
    ]
