# Generated by Django 5.1.1 on 2025-08-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0027_fooditem_max_time_fooditem_min_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='cash_activated',
            field=models.BooleanField(default=False),
        ),
    ]
