# Generated by Django 5.1.1 on 2025-09-02 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_box', '0001_initial'),
        ('theatre', '0028_theatre_cash_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chatuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_box.chatuser'),
        ),
    ]
