# Generated by Django 5.1.1 on 2025-09-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0029_order_chatuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
