# Generated by Django 5.1.1 on 2025-11-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0032_order_comment_order_rating_order_review_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='download_invoice',
            field=models.BooleanField(default=True),
        ),
    ]
