# Generated by Django 5.1.1 on 2024-12-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0002_detail_notification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutlogs',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
