# Generated by Django 5.1.1 on 2025-01-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0004_paymentgateway_remove_payment_razorpay_order_id_and_more'),
        ('theatre', '0009_alter_fooditem_options_fooditem_priority_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_perscantage', models.FloatField(default=5)),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre')),
            ],
        ),
    ]
