# Generated by Django 5.1.1 on 2025-01-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0005_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='secondary_mobile',
            field=models.CharField(default='', max_length=100),
        ),
    ]
