# Generated by Django 5.1.1 on 2025-02-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0006_detail_secondary_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='break_start_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='scaning_service',
            field=models.BooleanField(default=True),
        ),
    ]
