# Generated by Django 5.1.1 on 2025-03-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0007_detail_break_start_time_detail_scaning_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpaydetail',
            name='payment',
        ),
        migrations.AddField(
            model_name='detail',
            name='payment_model',
            field=models.CharField(choices=[('theatre', 'Theatre'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='detail',
            name='state',
            field=models.CharField(default='Haryana', max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='break_start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='RazorpayDetail',
        ),
    ]
