# Generated by Django 5.1.1 on 2025-04-05 06:44

import adminPortal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0008_remove_razorpaydetail_payment_detail_payment_model_and_more'),
        ('theatre', '0014_payment_settlement_theatre_notification_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='notification_token',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='state',
        ),
        migrations.AddField(
            model_name='detail',
            name='logo',
            field=models.ImageField(default='theatre_logo/default.png', upload_to='theatre_logo/'),
        ),
        migrations.CreateModel(
            name='bankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default='', max_length=100)),
                ('account_name', models.CharField(default='', max_length=100)),
                ('ifsc_code', models.CharField(default='', max_length=100)),
                ('bank_name', models.CharField(default='', max_length=100)),
                ('branch_name', models.CharField(default='', max_length=100)),
                ('theatre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to=adminPortal.models.document_upload_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='GSTDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_number', models.CharField(default='', max_length=100)),
                ('pan', models.CharField(default='', max_length=100)),
                ('gst_state', models.CharField(default='', max_length=100)),
                ('state_code', models.CharField(default='', max_length=100)),
                ('gst_address', models.CharField(default='', max_length=100)),
                ('firm_name', models.CharField(default='', max_length=100)),
                ('theatre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre')),
            ],
        ),
    ]
