# Generated by Django 5.1.1 on 2025-04-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0009_remove_detail_notification_token_remove_detail_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstdetails',
            name='gst_state',
            field=models.IntegerField(),
        ),
    ]
