# Generated by Django 5.1.1 on 2025-04-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0010_alter_gstdetails_gst_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstdetails',
            name='gst_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gstdetails',
            name='state_code',
            field=models.IntegerField(),
        ),
    ]
