# Generated by Django 5.1.1 on 2025-04-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0011_alter_gstdetails_gst_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstdetails',
            name='state_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
