# Generated by Django 5.1.1 on 2025-05-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0012_alter_gstdetails_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detail',
            name='state',
            field=models.CharField(default='Haryana', max_length=100),
        ),
        migrations.AddField(
            model_name='detail',
            name='zip',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='access_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='gateway_salt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='working_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
