# Generated by Django 5.1.1 on 2025-06-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0013_detail_city_detail_state_detail_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstdetails',
            name='gst_address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
