# Generated by Django 5.1.1 on 2025-09-11 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0015_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='razorpay_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='selected_gateway',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminPortal.paymentgateway'),
        ),
        migrations.AddField(
            model_name='detail',
            name='settlement_model',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Split', 'Split')], default='Manual', max_length=10),
        ),
    ]
