# Generated by Django 5.1.1 on 2025-09-02 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatre', '0028_theatre_cash_activated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('reply_required', models.BooleanField(default=False)),
                ('continue_chat', models.BooleanField(default=False)),
                ('auto_reply', models.BooleanField(default=True)),
                ('last_msg_tym', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('seen_status', models.BooleanField(default=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('msg_type', models.CharField(choices=[('INCOMING', 'INCOMING'), ('OUTGOING', 'OUTGOING'), ('TEMPLATE', 'TEMPLATE')], max_length=10)),
                ('template', models.CharField(blank=True, choices=[('CONFIRMATION', 'CONFIRMATION'), ('REFUND', 'REFUND')], default='', max_length=15, null=True)),
                ('chat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_box.chatuser')),
                ('order', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='theatre.order')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
